### ISSUE TITLE
Premier balisage des livres 21 à 30

### ISSUE THREAD

**Issue by lafrering** [Chartes-TNAH/tite-live#13]
Premier balisage des livres 21 à 30. Attention, le schéma et la dtd ont été mis entre crochet, en attendant une solution pour avoir un fichier conforme au schéma Perseus

**Comment by aimelle** [comment]
Je vais juste re-push avec une petite modification, parce que dans le changelog t'avais les deux `<change>` qui étaient emboîtés l'un dans l'autre.

**Comment by lafrering** [comment]
Au temps pour moi, merci ;)
