### ISSUE TITLE
Encodage des corrections

### ISSUE THREAD

**Issue by aimelle** [Chartes-TNAH/tite-live#17]
Coucou,

Actuellement les corrections sont sous cette forme : `<corr sic="tur">tum</corr>` et après m'être laborieusement promenée sur les guidelines Epidoc + en ayant testé empiriquement si c'était possible dans nos documents de faire `<corr sic="">` (non) j'ai conclu qu'on n'allait pas pouvoir laisser ça comme ça, du coup je vous mets les pages des guidelines rencontrées au cours de mon enquête : 
[http://www.stoa.org/epidoc/gl/latest/trans-correction.html?search=corr&go=search](url)
[http://www.stoa.org/epidoc/gl/latest/trans-regularization.html](url)
[http://www.stoa.org/epidoc/gl/latest/supp-app-inline.html](url)
et puis `<corr>` dans les guidelines TEI [http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-corr.html](url)

En concluez-vous comme moi qu'il faut transformer les `<corr sic="tur">tum</corr>` en `<choice><sic>tur</sic><corr>tum</corr></choice>` ?
(Si oui j'ai une regex 👌 : `<corr sic="(.*?)">(.*?)((\n| |)*?)</corr>` ==> `<choice><sic>$1</sic><corr>$2</corr></choice>`)

**Comment by lafrering** [comment]
Merci de soulever le problème. D'après mes souvenirs de cours de TEI avec M. Camps, les corrections se font comme ceci (c'est aussi écrit dans les guidelines Epidoc, cf. http://www.stoa.org/epidoc/gl/latest/supp-app-inline.html ) : `<choice><orig>tur</orig><reg>tum</reg></choice>` .
Du coup, on peut sans doute adapter la regex que tu proposes en : `<corr sic="(.*?)">(.*?)((\n| |)*?)</corr>` ==> `<choice><orig>$1</orig><reg>$2</reg></choice>`. Qu'en dites-vous ? Peut-être que je fais fausse route... 
PS : je vote pour l'élaboration d'un t-shirt "keep calm there's a Regex for this".

**Comment by PonteIneptique** [comment]
Attention ! `corr` et `sic` n'ont pas le même sens que `reg` et `orig`.
- `corr` et `sic` signifie une erreur dans le manuscrit (ou l'OCR) et une correction proposée par l'éditeur-rice
- `orig` et `reg` signifie qu'un orthographe particulier avait été choisi par l'auteur-e mais qu'il est régularisé (version la plus acceptée) par l'éditeur-rice

**Comment by lafrering** [comment]
Après discussion avec @aimelle, nous allons encoder comme écrit plus haut, à savoir `<choice><sic>tur</sic><corr>tum</corr></choice>` puisqu'il nous semble que c'est une erreur d'OCR. J'espère que cela convient... Merci beaucoup pour vos explications.
