### ISSUE TITLE
Anomalie dans l'index notarum

### ISSUE THREAD

**Issue by aimelle** [Chartes-TNAH/tite-live#19]
C'est un peu anecdotique mais je parcoure les fichiers à la recherche de choses incorrectes, et je remarque que dans les deux premiers fichiers où on a l'index notarum, on a ça : 

```
<p><hi rend="italics">V</hi> = Veronensis saec. V.</p>
<p><hi rend="italics">M</hi> = Mediceus saec. XI.</p>
<p><hi rend="italics">C</hi> = Colbertinus saec. XI.</p>
<p><hi rend="italics">P</hi> = Parisiensis saec. X.</p>
```

et au milieu, perdu : 

```
<p><foreign lang="greek">s</foreign> = codices recentes (vel omnes vel singuli) vel editiones
veteres.</p>
```

Ce qui a attiré mon attention d'abord c'est qu'on peut pas laisser `lang="greek"` il faudrait plutôt `xml:lang` ; mais surtout est-ce que ça ne serait pas une erreur ? En quoi ce "s" est-il du grec ? Est-ce qu'il faudrait pas juste mettre les mêmes balises `<hi rend="italics">` que partout ailleurs ? @lafrering surtout puisque c'est dans les livres 21-30 qu'il y a aussi cet index.

**Comment by PonteIneptique** [comment]
@aimelle c'est tout à fait bien vu. Je ne sais pas à quel point vous êtes familiers avec ce genre de notation donc je me permets de les expliquer. Les V, M, C et P sont en fait des sigles utilisés pour identifier des manuscrits (Les lettres vont de paire avec le nom de la ville de conservation généralement : P pour Paris et la BNF, Veronensis pour Vérone, etc.)

Le `s` cependant est en fait un `ς` (sigma) que l'encodage à l'époque (avant l'UTF-8 que l'on connaît aujourd'hui) ne permettait pas d'encoder et que Perseus marquait alors `<foreign lang="greek">s</foreign>`. Il correspond ici aux éditions et livres plus récents que les manuscrits et qui peuvent servir des fois de support pour proposer une correction

Donc, si c'était dans le corps de texte, il aurait fallu transformer en Grec via un convertisseur Betacode ( de ce type : https://zfletch.github.io/beta-code-converter-js/ ). En revanche là, il faudrait plutôt le convertir effectivement en `<hi rend="italics">ς</hi> = ...`

**Comment by aimelle** [comment]
Merci, nous allons faire comme ça ! De fait notre degré de familiarité avec l'identification des manuscrits est … faible. (Je laisse cette issue ouverte au cas où on aurait besoin du convertisseur Betacode — je sais qu'on a des `&mdash;` dans le corps du texte, mais il y a peut-être quelques caractères grecs on ne sait jamais.)
