### ISSUE TITLE
Edition numérisée du texte 

### ISSUE THREAD

**Issue by lafrering** [Chartes-TNAH/tite-live#20]
Comme @aimelle l'a soulevé dans #19  (anomalies de l'index notarum et des caractères grecs qui se baladent dans le texte), je pense qu'il serait bien d'avoir le texte d'édité par Teubner en 1884 pour savoir ce qu'il en est véritablement des caractères grecs et de l'index. Pour savoir si ceux-ci sont présents tels quels dans l'édition papier, ou s'il s'agit d'une erreur d'OCR. Il serait dommage de prendre une mauvaise décision à propos de quelque chose d'essentiel au texte. 
@PonteIneptique vous nous disiez que vous pourriez faire appel à des collègues américains qui auraient accès à HathiTrust. J'ai trouvé un lien vers HathiTrust correspondant à l'édition en question : https://catalog.hathitrust.org/Record/011665746  Je ne sais cependant pas si c'est ce dont vous avez besoin pour avoir accès aux images. 
Pourriez-vous nous transmettre des images du texte numérisé ? Un grand merci d'avance !

**Comment by PonteIneptique** [comment]
Envoyez moi un mail que je vous transmette un lien de manière privée...
