### ISSUE TITLE
Le corps du texte, suite et presque fin

### ISSUE THREAD

**Issue by aimelle** [Chartes-TNAH/tite-live#25]
Dans le même esprit que l'issue sur le TEI Header, voilà l'issue sur à peu près tout ce qu'il nous reste à régler concernant le texte lui-même (à l'exception des quelques entités qui correspondent à des caractères spéciaux, ce qui sera notre dernier problème.)
Comme précédemment, **on n'indente surtout pas** et on est en mode regex / le point = tout la plupart du temps.

D'abord, on change l'encodage des corrections [comme déterminé dans l'issue #17](https://github.com/Chartes-TNAH/tite-live/issues/17) : 
`<corr sic="(.*?)">(.*?)((\n| |)*?)</corr>`
==>
`<choice><sic>$1</sic><corr>$2</corr></choice>`

Ensuite,

- `<pb>` = page beginning / http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-pb.html. En Epidoc, cette balise n'accepte pas `id` comme attribut, mais `n` ; on peut donc remplacer par n="1" : 
`<pb id="p.([0-9]+)"/>`
==>
`<pb n="$1"/>`

- Il faut mettre des `<p></p>` dans chaque `<div type="textpart" subtype="section">` ET dans les `<div type="textpart" subtype="book">` qui ne contiennent pas de `<div>`
(1) d'abord on supprime les `<p/>` qu'on avait conservés au cas au, rechercher/remplacer par rien.
(2) mettre des `<p>` dans les sections :
`(<div type="textpart" subtype="section" .*?>)(.*?)(</div>)`
==>
`$1<p>$2</p>$3`
(3) puis mettre des `<p>` dans les books sans chapters ni sections :
**/// EXCLURE L'INDEX quand on est dans un fichier qui en a un, sélectionner tout à partir de après le book index ///**
`(<div type="textpart" subtype="book" n="[0-9]+[a-z]">)((\n| |)*?)(<head>(.*?)</head>)(.*?)(</div>)`
==>
`$1$4<p>$6</p>$7`

- On a parfois des `<hi>` qui chevauchent des `<p>` ; si dans vos documents vous vous apercevez qu'il y en a beaucoup (rechercher : `></hi>`) on pourra récfléchir à une autre solution, mais là sur livy.teub01-10 j'en ai 5 donc j'ai choisi de faire les corrections à la main c'est plus simple (d'autant qu'en cherchant `></hi>` on peut aussi tomber sur des choses qui ne posent en fait pas problème, il faut regarder au cas par cas si il y a un problème de chevauchement de balises ou non.)

- Enfin pour la propreté du truc, on peut supprimer les espaces en trop : 
(1) Supprimer les espaces entre différentes balises : 
`>\s+<`
==>
`><`
(2) Supprimer les espaces avant les balises fermantes : 
`\s+</`
==>
`</`
(3) Supprimer les espaces après les `<p>` : 
`(<p>)\s+`
==>
`$1`

- Après il y a une dernière question que je me posais, au sujet des `<pb/>` ; au début je m'étais dit qu'il fallait fermer les `<p>` quand on rencontre un `<pb/>`, mais d'abord en termes juste de structure du texte c'est pas forcément pertinent vu qu'un paragraphe peut continuer après un changement de page, et puis les `<pb/>` : c'est une milestone donc au fond c'est pas un problème que y en ait au milieu des `<p>` ; on laisse comme ça ?

Voilà, donnez-moi votre avis et surtout prévenez-moi s'il y a quelque chose qui ne marche pas / casse tout chez vous.

**Comment by aimelle** [comment]
Ha et, normalement, après avoir fait le marquage des book / chapter / section + ça, on a se retrouve avec un document qu'on PEUT indenter, tout propre et beau, joie sur la terre (les seuls problèmes qui restent normalement seront les entités, mais normalement ce sera surtout des &mdash; qui traînent + des choses dans le TEI Header.)

**Comment by lafrering** [comment]
- Pour le `<pb/>`, je trouve que n="1" est plus satisfaisant que n="p.1", parce qu'on rajoute 2 caractères qui ne me semblent pas pertinents. Dans les guidelines TEI, dans l'exemple qui est utilisé, le pb est marqué  comme ça n="1". 

- Pour les `<p> </p>` dans les div, je suis d'accord (joie).

- Pour les `<hi>` qui se chevauchent : moi aussi j'en ai 5 dans 21-30 mais j'ai l'impression qu'il s'agit de balises où il n'y a rien dedans. Donc, je ne sais pas vraiment à quoi cela correspond. Exemple : `populo crearetur,<hi rend="italics"></hi> qui pro dictatore esset`. 

- Concernant les `<p>` et les `<pb/>`, à mon avis, ça ne pose pas de problème de structure étant donné que c'est une balise valide. Et puis je pense qu'il faut absolument garder les pb car c'est une donnée importante. 

- Pour l'indentation, je me demande s'il ne vaudrait pas mieux attendre avant d'indenter chacune de notre côté puisqu'à un moment donné, il faudra tout réunir dans un seul fichier. Parce qu'au final, l'indentation n'est que cosmétique si le fichier est conforme au départ.

**Comment by aimelle** [comment]
D'accord pour le `n="1"`, c'est vrai que c'est plus clean.
Perso les `<hi>` vides je pense qu'on les supprime ? Si ils servent à rien ben, ils servent à rien.
(Et loin de moi l'idée de supprimer les `<pb/>` haha.)

**Comment by AlyxTaj** [comment]
J'ai fait toutes les regex nécessaires sur les books 31-38. Je n'avais que quelques `<hi>` qui chevauchaient des `<p>` donc je les ai reprises à la main, aucune vide.
En effet il vaut mieux laisser les `<pb>` en l'état.
Je préfère attendre encore avant d'indenter parce que ça m'a plombé toute mon après-midi...
Merci pour tout !
