### ISSUE TITLE
UTF-8 pour les caractères spéciaux 

### ISSUE THREAD

**Issue by lafrering** [Chartes-TNAH/tite-live#44]
Bonjour @PonteIneptique, concernant la présence d'entités de type HTML `&eacute`, par exemple, dans le corps du texte, nous nous posons la question suivante : pouvons-nous, au niveau de la déclaration xml écrire ceci `<?xml version="1.0" encoding="UTF-8"?>` pour régler les soucis de validation du fichier xml (avec Oxygen) ? 
Et une fois cela fait, pouvons-nous remplacer ces entités par les caractères spéciaux correspondants ? 
Merci.

**Comment by PonteIneptique** [comment]
Oui et Oui !

**Comment by aimelle** [comment]
Parfait, merci !
