### ISSUE TITLE
Unification en un seul fichier

### ISSUE THREAD

**Issue by aimelle** [Chartes-TNAH/tite-live#45]
Bonjour @PonteIneptique ,

Une fois tous les documents xml correctement encodés, l'unificiation en un seul fichier sera simple. Cependant quelques questions se posent : 

(1) D'abord, celle des **titres des volumes** de l'édition papier. En effet, rien ne change dans le `TEI header` selon les documents, sauf la mention du titre, et précisément dans celui-ci l'indication des livres contenus dans le tome : 

Titi Livi ab urbe condita libri editionem priman curavit
Guilelmus Weissenborn editio altera auam curavit Mauritius Mueller
**Pars III. Libri XXXI-XL.** Editio Stereotypica

par exemple.

Comment faire pour ne pas perdre cette information ?

(2) Par ailleurs, dans le cadre de cette unification en un fichier et dans la perspective de la capitainisation, nous pensions rajouter deux niveaux de `<div>` : une `<div type="edition">` qui engloberait tout, puis 4 `<div type="part" n="">` correspondant aux 4 volumes.
Est-ce une bonne façon de procéder ?

(3) Que faire des changelogs ? Pour le moment nous en avons sur chaque fichier, mais si on rassemble tout dans un seul est-ce qu'on les copie/colle juste tous les uns à la suite des autres ? devrions-nous spécifier dans nos `<change>` sur quel fichier nous travaillons pour que ça ne soit pas trop confus ?

Merci !

**Comment by PonteIneptique** [comment]
1. Je pense que vous pouvez garder le titre du premier volume. Vous pouvez changer sourceDesc pour refléter ce changement
2. Cela me semble très bien.
3. Vous pouvez les regrouper et effectivement ajouter une mention spécifique si besoin du fichier ciblé.

**Comment by lafrering** [comment]
Peut-on écrire dans le sourceDesc `<biblScope type="volume">4</biblScope>` puisqu'il y'a 4 parties ? 
Et pour ne pas perdre les titres des 3 derniers volumes, peut-on écrire "Pars I-IV. Libri I-XL." ?

**Comment by PonteIneptique** [comment]
Bonne idée et oui aux deux.

**Comment by lafrering** [comment]
Très bien, nous ferons ça. Merci !
