### ISSUE TITLE
Fichiers __cts__.xml

### ISSUE THREAD

**Issue by lafrering** [Chartes-TNAH/tite-live#46]
Bonjour @PonteIneptique,
Nous nous penchons sur les fichiers cts, tout d'abord que signifie ti : `<ti:textgroup>`
Pour les URN : 

- Est-ce qu'on utilise bien l'identifiant Perseus de Tite-Live, phi0914 ? http://catalog.perseus.org/catalog/urn:cite:perseus:author.840

- En conséquence, pour le niveau work, l'identifiant serait alors phi001 ? (exemple : https://github.com/PerseusDL/canonical-latinLit/blob/master/data/phi0914/phi001/__cts__.xml )

- Et pour le niveau version, s'agit-il de l'édition Teubner (1884) ? Si oui existe-t-il un identifiant ? Sinon doit-on l'inventer ?

**Comment by PonteIneptique** [comment]
`ti:` est un préfixe xml. Il est relié au namespace `xmlns:ti="http://chs.harvard.edu/xmlns/cts" ` dans le document que vous avez joint ( https://github.com/PerseusDL/canonical-latinLit/blob/master/data/phi0914/phi001/__cts__.xml#L1 ). Cela permet d'avoir plusieurs namespaces dans un même document XML. 

Dans les guidelines de Capitains, `http://chs.harvard.edu/xmlns/cts` est défini comme namespace par défaut via `xmlns="http://chs.harvard.edu/xmlns/cts"`. Mais les deux sont valides. En effet, tant que `textgroup` appartient à `http://chs.harvard.edu/xmlns/cts`, tout marchera correctement. On aurait même pu utiliser le préfixe `xmlns:enc="http://chs.harvard.edu/xmlns/cts"` que cela ne casserait rien.

En conséquence, vous avez trouvé les bons liens et je vous conseille de ne pas réinventer la roue : réutiliser les `__cts__.xml` de phi0914 et de phi0914.ph001. Pour l'identifiant de cette version, vous pouvez utiliser `phi0914.phi001.perseus-lat1`, il me semble que c'est l'édition présentée ici http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A1999.02.0169%3Abook%3D1%3Achapter%3D1%3Asection%3D1

**Comment by lafrering** [comment]
Merci pour vos explications, nous ferons ainsi.

**Comment by lafrering** [comment]
Bonjour @PonteIneptique 
Est-ce les fichiers cts doivent ressembler à cela ? Y'a-t-il des choses à affiner ? 

Pour le textgroup : 
`<ti:textgroup xmlns:ti="http://chs.harvard.edu/xmlns/cts" projid="latinLit:phi0914" ``urn="urn:cts:latinLit:phi0914">`
   ` <ti:groupname xml:lang="lat">Titus Livius</ti:groupname>`
`</ti:textgroup>`

Pour le work : 
`<ti:work xmlns:ti="http://chs.harvard.edu/xmlns/cts" groupUrn="urn:cts:latinLit:phi0914"` `projid="latinLit:phi001" urn="urn:cts:latinLit:phi0914.phi001" xml:lang="lat">`
		`<ti:title xml:lang="lat">Ab urbe condita</ti:title>`
		`<ti:edition urn="urn:cts:latinLit:phi0914.phi001.perseus-lat1" ``workUrn="urn:cts:latinLit:phi0914.phi001">`
	     ` <ti:label xml:lang="lat">Ab urbe condita</ti:label>`
	     ` <ti:description xml:lang="lat">Titi Livi ab urbe condita libri editionem priman curavit`
									`Guilelmus Weissenborn editio altera auam curavit ``Mauritius Mueller`
									`Pars I-IV. Libri I-XL. Editio Stereotypica. ``1884-1911.``</ti:description>`

`<ti:memberof collection="Perseus:collection:Greco-Roman" />`
`</ti:edition>`
`</ti:work>`

PS : il y a des ` en trop dans le commentaire, ce n'est pas le cas dans le fichier, ne vous inquiétez pas :)

**Comment by PonteIneptique** [comment]
Cela me semble correct à première vue.
Sauf pour ce qui me semble être une typo (plusieurs fois des \`\` traînent)

**Comment by PonteIneptique** [comment]
Je viens de voir le PS.

**Comment by PonteIneptique** [comment]
Je vous rappelle que pour afficher du code comme ca, la bonne méthode est : 
 \`\`\`xml
\`\`\`

**Comment by lafrering** [comment]
Merci bien !
