### ISSUE TITLE
Encodage des livres 41 à 45

### ISSUE THREAD

**Issue by aimelle** [Chartes-TNAH/tite-live#49]
Bonjour @PonteIneptique ,
En essayant de faire les mêmes regex sur le dernier fichier xml que sur les autres, je me suis aperçue qu'il n'était pas encodé comme les autres. En effet, il est encodé de manière très imprécise, avec des `<sic>` sans `<corr>` et des balises `<q>`. Je n'ai évidemment pas l'intention de changer cela, mais je voulais savoir si je pouvais signaler quelque part (dans le TEI header, peut-être dans un `noteStmt` ? Car comme ça m'a étonnée, je me dis que ça risque d'étonner d'autres gens dans le futur.

**Comment by PonteIneptique** [comment]
Cela me semblerait être une bonne pratique effectivement

**Comment by aimelle** [comment]
Je ferai ça alors, merci !
