### ISSUE TITLE
Finitions / 01-10, 39-40 et 41-45

### ISSUE THREAD

**Issue by aimelle** [Chartes-TNAH/tite-live#54]
01-10 : 
-  encodage du TEI Header (adapté à l'unification en un seul fichier) (issue #18)
-  remplacement des entités par les caractères correspondants

39-40 : 
-  correction des balises `<sic corr="">` en choice-sic-corr
-  remplacement des entités html par les caractères correspondants
-  mise entre balises commentaires de certaines parties du TEI Header
-  ajout d'un attribut `reason="lost"` dans les balises `<gap/>` (issue #53)

41-45 : 
-  remplacement des entités html par les caractères correspondants
-  mise entre balises commentaires de certaines parties du TEI Header
-  ajout d'un attribut `reason="lost"` dans les balises `<gap/>`

**Comment by lafrering** [comment]
Je ferme l'issue du coup.
