### ISSUE TITLE
Unification en un seul fichier

### ISSUE THREAD

**Issue by aimelle** [Chartes-TNAH/tite-live#59]
J'ai unifié nos 5 fichiers en un seul, en ajoutant une balise englobante `<div type="edition">` et 5 balises `<div type="textpart" type="part" n=" ">` (cf issue #45) ; pour le nom du fichier cf issue #46. J'ai unifié les changelogs en essayant d'en perdre le moins possible, et j'ai aussi ajouté un `noteStmt` à propos de l'encodage des livres 39 à 45.

note pour moi-même : il faudra que j'ajoute une note au sujet des balises gap (cf issue #53.)

**Comment by lafrering** [comment]
Par contre, je crois que ce n'est pas le bon fichier que tu as push

**Comment by aimelle** [comment]
Ha oui de fait c'est unfortunate
