### ISSUE TITLE
ELEMENTS DOCTYPE

### ISSUE THREAD

**Issue by AlyxTaj** [Chartes-TNAH/tite-live#6]
Comment gérer les doctypes en début de fichier XML ?

**Comment by AlyxTaj** [comment]
La doctype est bien à conserver. Je me réfère au wiki de la TEI-conversion-tools de PerseusDL
https://github.com/PerseusDL/tei-conversion-tools/wiki/Invalid-XML-or-Incomplete-(%3F)-Data

Celle-ci doit en toute logique être placée entre la déclaration `<?xml>` et la balise TEI

Il faut aussi ajouter deux entités présentes plus bas qui correspondent au  `&responsibility;
	&fund.NEH;` et au `&Perseus.publish;`
Il s'agit de : 
`<!ENTITY fund.NEH
    '<funder
n="org:NEH"
>The National Endowment for the Humanities</funder>' >`

et 

`<!ENTITY	Perseus.publish
		"<publicationStmt>
		<publisher>Trustees of Tufts University</publisher>
		<pubPlace>Medford, MA</pubPlace>
		<authority>Perseus Project</authority>
		</publicationStmt>"	`

Cela devrait régler un certain nombre de soulignements !

**Comment by AlyxTaj** [comment]
Pardon,

Pour l'élément `&responsibility`
Celui-ci doit être annoncé dans DOCTYPE comme ceci : 
`<!ENTITY responsibility
		"<sponsor>Perseus Project, Tufts University</sponsor>
		<principal>Gregory Crane</principal>
		<respStmt>
		<resp>Prepared under the supervision of</resp>
		<name>Lisa Cerrato</name>
		<name>William Merrill</name>
		<name>Elli Mylonas</name>
		<name>David Smith</name>
		</respStmt>"`

**Comment by aimelle** [comment]
De mon côté j'avais compris qu'on devait remplacer les entités par des balises TEI classiques, type 

`<respStmt>
 <resp></resp>
 <persName></persName>
</respStmt>`

Qu'en est-il @PonteIneptique ?

**Comment by PonteIneptique** [comment]
@aimelle @AlyxTaj Les deux sont possibles. À vrai dire, il vaudrait mieux tout simplement remplacer les `&responsibility;` par la valeur dans la DTD `<publicationStmt> <publisher>Trustees of Tufts University</publisher> <pubPlace>Medford, MA</pubPlace> <authority>Perseus Project</authority> </publicationStmt>` de manière à ne plus avoir à gérer ces entités...

**Comment by lafrering** [comment]
Je rouvre l'issue parce que, finalement, nous n'avons pas encore réglé la question du `&responsibilty` et que c'est mieux d'avoir accès au infos facilement ;)

**Comment by lafrering** [comment]
Bonjour @PonteIneptique 
Si nous devons en effet faire figurer un `RespStmt` dans le header, devrions-nous : 
(1) Transformer le changelog de Gregory Crane en `RespStmt` ?
(ci-dessous ce qui est dans le fichier original)
`<revisionDesc>
<change>
	<date>2006/7/19</date>
	<respStmt><name>Gregory Crane</name><resp>ed.</resp></respStmt>
	<item>

</item>
</change>`

(2) Dans `RespStmt`, ajouter nos noms pour le passage de TEI P4 à Epidoc ?

**Comment by PonteIneptique** [comment]
Si vous ajoutez une entrée xml:id="GregoryCrane" dans le RespStmt, vous pouvez simplement écrire : 

```xml
<change who="#GregoryCrane" when="2006-07-19">Edition</change>
```
Mais je pense qu'ici vous pouvez simplement transformer en 

```xml
<change who="Gregory Crane" when="2006-07-19">Edition</change>
```

car c'est ce que cela veut dire ;)

**Comment by aimelle** [comment]
Nous mettrons ce changelog en conformité avec le schema Epidoc, mais nous restons un peu hésitantes sur ce qu'il convient de mettre dans le `RespStmt` ; quelque chose comme ça : 

    <respStmt>
        <name xml:id="GregoryCrane">Gregory Crane</name>
        <resp>Edition</resp>
    </respStmt>
    <respStmt>
        <name xml:id="LeaFrering">Léa Frering</name>
        <resp>Passage de TEI P4 à Epidoc</resp>
    </respStmt>

?

**Comment by AlyxTaj** [comment]
Les RespStmt ont été établis.
Issue closed.
